<!-- Socket.io -->
<script src="/socket.io/socket.io.js"></script>

<!-- cmd-queue.js -->
<script src="/resources/cmd-queue/cmd-queue.js"></script>

<!-- Tether -->
<script src="/common/tether/dist/js/tether.js"></script>

<!-- px2style -->
<script src="/resources/px2style/scripts.js"></script>

<!-- project common -->
<script src="/common/scripts/main.js"></script>

<!-- Bootstrap 3 JS. -->
<script src="/resources/bootstrap/js/bootstrap.min.js"></script>
