		<header class="clearfix theme-header">
			<div class="theme-header__ci">
				<a href="/">
					<p class="theme-header__ci__service-name">{{ conf.app.name }}</p>
					<p class="theme-header__ci__project-name">-</p>
				</a>
			</div>
			<div class="theme-header__shoulder">
				<p><button class="px2-btn" onclick="window.main.logout();">ログアウト</button></p>
			</div>
		</header>
		<div class="theme-main">
