		<header class="clearfix theme-header">
			<div class="theme-header__ci">
				<a href="/">
					<p class="theme-header__ci__service-name"><%= conf.app.name %></p>
					<p class="theme-header__ci__project-name">-</p>
				</a>
			</div>
			<div class="theme-header__shoulder">
				<ul>
					<li><input type="text" class="form-control px2dt-pages-filter" placeholder="Filter" /></li>
					<li><button class="px2-btn" onclick="window.location.href='/logout.html';">ログアウト</button></li>
				</ul>
			</div>
		</header>
		<div class="theme-main">
