<!-- config -->
<script type="text/javascript">
window.config = new (function(){
    var rtn = {};
    rtn.urlPreview = '{{ conf.px2server.origin }}';
    return rtn;
})();
</script>

<!-- Required meta tags always come first -->
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
<meta http-equiv="x-ua-compatible" content="ie=edge" />

<!-- Bootstrap 4 CSS -->
<link rel="stylesheet" href="/resources/bootstrap/css/bootstrap.css" />

<!-- px2style -->
<link rel="stylesheet" href="/resources/px2style/styles.css" type="text/css" />

<!-- project common -->
<link rel="stylesheet" href="/common/styles/common.css" type="text/css" />
