		<header class="theme-header">
			<div class="theme-header__inner clearfix">
				<div class="theme-header__px2logo">
					<a href="/"><img src="/common/images/logo.svg" alt="<%= conf.app.name %>" /></a>
				</div>
				<div class="theme-header__ci">
					<a href="/">
						<p class="theme-header__ci__project-name">-</p>
					</a>
				</div>
				<div class="theme-header__shoulder">
					<ul>
						<li><input type="text" class="form-control px2dt-pages-filter" placeholder="Filter" /></li>
						<li><button class="px2-btn" onclick="window.location.href='/logout.html';">ログアウト</button></li>
					</ul>
				</div>
			</div>
		</header>
		<div class="theme-main">
