<!-- Required meta tags always come first -->
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
<meta http-equiv="x-ua-compatible" content="ie=edge" />

<!-- Bootstrap 4 CSS -->
<link rel="stylesheet" href="/common/bootstrap/dist/css/bootstrap.css" />

<!-- px2style -->
<link rel="stylesheet" href="/common/px2style/dist/styles.css" type="text/css" />
<script src="/common/px2style/dist/scripts.js"></script>

<!-- project common -->
<link rel="stylesheet" href="/common/styles/common.css" type="text/css" />
